[package]
name = "gri"
version = "0.1.0"
authors = ["Vadim Slynko <vadim@slynko.rocks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
simple_logger = "1.6.0"
structopt = "0.3.15"